Add custom coding matrix support
klauspost/reedsolomon pull request #187
Opened 2022-06-16 16:31 UTC by vitalif

2022-06-16 16:47 UTC, klauspost requested changes
What is the use case for this, if I may ask?

Please add test.

2022-06-16 16:47 UTC, klauspost commented on options.go
> +func WithCustomMatrix(customMatrix [][]byte) Option {
Please document usage.

2022-06-16 21:20 UTC, vitalif commented on options.go
> +func WithCustomMatrix(customMatrix [][]byte) Option {
Ok, added a comment :-)

2022-06-16 21:22 UTC, vitalif commented
I think there are at least 2 use cases:
1) interoperability with other libraries that generate the matrix differently or do other hypothetical nasty things like swapping rows
2) LRC (local reconstruction codes) where some parity rows only span several, but not all, data chunks

I added a test, please take a look :-)

2022-06-17 09:10 UTC, klauspost approved these changes
LGTM

2022-06-17 09:43 UTC, merged